export const siteConfig = {
  name: "INDUFLOW",
  tagline: "Fournitures industrielles, détection des gaz et étalonnage au Maroc",
  taglineAlt: "Industrial Supply, Detection & Calibration",
  topBarMessage: "Solutions industrielles pour professionnels au Maroc",
  phone: "+212 5 XX XX XX XX",
  phoneHref: "tel:+2125XXXXXXXX",
  email: "contact@induflow.ma",
  whatsappNumber: "+212 6 XX XX XX XX",
  whatsappHref: "https://wa.me/2126XXXXXXXX",
  address: "148 Rue Zoubir Bnou El Ouam, Roches Noires, Rdc N1, Casablanca",
  streetAddress: "148 Rue Zoubir Bnou El Ouam, Roches Noires, Rdc N1",
  city: "Casablanca",
  postalCode: "20300",
  region: "Casablanca-Settat",
  identifiantFiscal: "66288720",
  ice: "003723126000093",
  url: "https://induflow.site",
  keywords: [
    "équipements industriels Maroc",
    "détecteur de gaz Maroc",
    "étalonnage détecteur de gaz Casablanca",
    "fournisseur industriel Casablanca",
    "pompes industrielles Maroc",
    "vannes industrielles Maroc",
    "EPI sécurité industrielle Maroc",
    "fourniture industrielle sur devis Maroc",
  ],
};

export const stats = [
  { value: "6+", label: "Catégories de produits et services" },
  { value: "100+", label: "Références à venir" },
  { value: "24h", label: "Réponse sous 24 h" },
  { value: "Maroc", label: "Livraison au Maroc" },
];
